# -*- coding: utf-8 -*-
from header_quests import *
from header_operations import *
from module_constants import *

talk_topics = [ 
 ("topic1", "{!}blank_quest", qf_random_quest,"{!}placeholder"), 
 
 ("szlachta_mieszczka_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"), 
 ("mieszczka_szlachta_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"), 
 ("mieszczka_mieszczka_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"), 
 ("mieszczka_biedak_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"), 
 ("mieszczanin_biedak_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("biedak_mieszczanin_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("biedak_biedak_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("mieszczanin_mieszczka_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("mieszczanin_mieszczka_2", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_mieszczanin_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_mieszczanin_2", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_mieszczanin_3", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("biedak_mieszczka_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_biedak_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("biedak_szlachcic_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_szlachta_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_szlachta_2", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("szlachta_szlachcianka_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_2", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_3", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_4", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_5", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_6", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_7", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("III_etap_szlachta_szlachta_8", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("IV_etap_szlachta_szlachta_1", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 ("IV_etap_szlachta_szlachta_2", "{!}blank_quest", qf_random_quest,"{!}placeholder"),
 
 
 ("topics_end", "{!}blank_quest", qf_random_quest,
  "{!}placeholder"
  ), 
 ("topic_3Zdrajcy_szlachta_szlachta", "{!}blank_quest", qf_random_quest,
  "{!}placeholder"
  ), 
 ("topic_3Zdrajcy_szlachta_mieszczanka", "{!}blank_quest", qf_random_quest,
  "{!}placeholder"
  ), 
 ("topic_3Zdrajcy_szlachta_mieszczanin", "{!}blank_quest", qf_random_quest,
  "{!}placeholder"
  ), 

  
]

talk_scripts = [
("fill_string",[
	(store_script_param, ":topic",1),
	
	(agent_get_slot, ":r1", "$ScriptAgent",RandomBegin),
	(agent_get_slot, ":r2", "$ScriptAgent",RandomBegin+1),
	(agent_get_slot, ":r3", "$ScriptAgent",RandomBegin+2),
	# (agent_get_slot, ":r4", "$ScriptAgent",RandomBegin+3),
	# (agent_get_slot, ":r5", "$ScriptAgent",RandomBegin+4),
	# (agent_get_slot, ":r6", "$ScriptAgent",RandomBegin+5),
	# (agent_get_slot, ":r7", "$ScriptAgent",RandomBegin+6),
	# (agent_get_slot, ":r8", "$ScriptAgent",RandomBegin+7),
	# (agent_get_slot, ":r9", "$ScriptAgent",RandomBegin+8),
	# (agent_get_slot, ":r10", "$ScriptAgent",RandomBegin+9),
	
	(store_faction_of_party, ":fac", "$current_town"),
	(faction_get_slot, ":ltrp", ":fac", LastLoserTroop),
	(faction_get_slot, ":lat", ":fac", LastLoserAt),
	(faction_get_slot, ":wtrp", ":fac", LastWinnerTroop),
	(faction_get_slot, ":wat", ":fac", LastWinnerAt),
	(faction_get_slot, ":dtrp", ":fac", LastDefeatedTroop),
	(faction_get_slot, ":dat", ":fac", LastDefeatedAt),
	
	(str_store_troop_name, s30, ":ltrp"),
	(str_store_troop_name, s31, ":lat"),
	
	(str_store_troop_name, s32, ":wtrp"),
	(str_store_troop_name, s33, ":wat"),
	
	
	(str_store_troop_name, s34, ":dtrp"),
	(str_store_troop_name, s35, ":dat"),
	
	(try_begin),
		(eq, ":topic", "str_wyrok_1_1"),
		(store_faction_of_party, ":fac", "$current_town"),
		(try_begin),
			(eq, ":fac", "fac_kingdom_2"),
			(str_store_string, s20, "str_wyrok_rosja"),
		(else_try),
			(eq, ":fac", "fac_kingdom_3"),
			(str_store_string, s20, "str_wyrok_prusy"),
		(else_try),
			(eq, ":fac", "fac_kingdom_4"),
			(str_store_string, s20, "str_wyrok_austria"),
		(try_end),
			
	(else_try),
		(eq, ":topic", "str_wyrok_1_2"),
		(store_faction_of_party, ":fac", "$current_town"),
		(try_begin),
			(eq, ":fac", "fac_kingdom_2"),
			(str_store_string, s20, "@Imperium"),
		(else_try),
			(eq, ":fac", "fac_kingdom_3"),
			(str_store_string, s20, "@Królestwa"),
		(else_try),
			(eq, ":fac", "fac_kingdom_4"),
			(str_store_string, s20, "@Monarchii"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_1_1"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Paskudna"),
		(else_try),
			(str_store_string, s20, "@Parszywa"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_1_2"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@piwo zacne w tej mieścinie mają, wasze zdrowie dobrzy ludzie!"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@miód przedni  w okolicy mają"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@napić się można w dobrej kompanii"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_1_3"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Do czorta"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Do diabła"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Zaraza"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@diabli wezmą dalszą drogę."),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@nie ujadę tyle coby na popas stanąć w karczmie u Jankiela."),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_3_1"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Cholera"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Eh"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Święci pańscy"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@w zamtuzie zabawić nieco, nawet tego nie idzie"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@iść ryby na targ kupić, znowu stara kijem obije"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_3_2"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@siedzieć na rzyci"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@siedzieć i nosa z domu nie wystawiać"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@bezczynnie stać, jakież marnotrawstwo czasu"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_3_3"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@towary nie dojadą na czas"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@towarów nie dostarczą i ino straty będą"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@handel podupadnie, a babka mówiła, że sucha wiosna idzie"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_4_1"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@dzieci dom mi rozniosą"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@nie będę mogła pleć grządek"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@chłopi na targ grząskimi traktami nie zjadą"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_4_2"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@gdzie się durny włóczy po deszczu"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@pewno piwsko chleje w szynku i o dziatkach, ni świecie nie pamięta"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@licho wie gdzie jest i z kim to się zadaję, nauczę rozumu gdy wróci"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_4_3"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@tyle deszczu było"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@padało tyle"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@lało od świtu do nocy"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@za mojego życia nie pamiętam"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@nie było nigdy wcześniej"),
		(else_try),
			(eq, ":r2", 2),
			(str_store_string, s21, "@10 lat nie było"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_4_4"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@pewnikiem wszystkie trakty zamokną"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@trakty znowuż nieprzejezdne będą"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@znowu stać i czekać nam przyjdzie, bez pożytku nijakiego"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_4_5"),
		(val_mod, ":r1",2),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@W krzyżu łomie"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@W kościach łomie"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@eh, żyć się odechciewa"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@kiedyż wreszcie padać przestanie."),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_4_6"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@zamokniętej marchewki"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@zamokniętego grochu"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@mokrych kartofli"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_5_1"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Psia mać"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@do wszystkich diabłów"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@sobaczy los"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_weather_complain_5_2"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",3),
		(val_mod, ":r3",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Piwa"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Wina"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Wódki"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@taką"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@parszywą"),
		(else_try),
			(eq, ":r2", 2),
			(str_store_string, s21, "@psią"),
		(try_end),
		(try_begin),
			(eq, ":r3", 0),
			(str_store_string, s22, "@ale kiesa pusta"),
		(else_try),
			(eq, ":r3", 1),
			(str_store_string, s22, "@lecz grosza nie ma"),
		(try_end),
	(try_end),
	(try_begin),
		(eq, ":topic", "str_greeting_1_1"),
		(val_mod, ":r1",4),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Czołem"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Moje uszanowanie"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Czołem Panie Bracie"),
		(else_try),
			(eq, ":r1", 3),
			(str_store_string, s20, "@Witam waćpana"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_1_2"),
		(val_mod, ":r1",4),
		(val_mod, ":r2",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Wyborne"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Przednie"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Wspaniałe"),
		(else_try),
			(eq, ":r1", 3),
			(str_store_string, s20, "@Witam waćpana"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@dłużej w tym mieście"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@jeszcze kilka dni"),
		(else_try),
			(eq, ":r2", 2),
			(str_store_string, s21, "@wszystko co dobre swój koniec ma, czas w drogę"),
		(try_end),	
	(else_try),
		(eq, ":topic", "str_greeting_1_3"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Do czorta"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Diabli nadali"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Cholera"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@mogłoby popadać"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@coś dawno nie padało"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_1_4"),
		(val_mod, ":r1",2),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Nie ma nic do robienia"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Nic ciekawego niema"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@zaplutej"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@parszywej"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_1_5"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@trunki"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@miody"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@wina"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_2_1"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Witam, {s69}."),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Dzień dobry."),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Piękny dziś mamy dzień, {s69}."),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_2_2"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@na dzisiejszy bal"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@na dzisiejszą kolację"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@tylko w Paryżu piękne można kupić"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_2_3"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@piękna"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@cudowna"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@znakomita"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@piknik"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@przejażdżkę kolasą za miasto"),
		(else_try),
			(eq, ":r2", 2),
			(str_store_string, s21, "@spacer"),
		(try_end),	
	(else_try),
		(this_or_next|eq, ":topic", "str_greeting_3_1"),
		(eq, ":topic", "str_greeting_5_1"),
		(val_mod, ":r1",4),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Dobry dzień."),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Kłaniam się nisko."),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Witam."),
		(else_try),
			(eq, ":r1", 3),
			(str_store_string, s20, "@Dobry."),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_3_2"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Diabli nadali"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Do licha"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_3_3"),
		(val_mod, ":r1",3),
		(val_mod, ":r2",4),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Doskonała pogoda"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Świetna pogoda"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Znakomita pogoda"),
		(try_end),
		(try_begin),
			(eq, ":r2", 0),
			(str_store_string, s21, "@piwo"),
		(else_try),
			(eq, ":r2", 1),
			(str_store_string, s21, "@ryby"),
		(else_try),
			(eq, ":r2", 2),
			(str_store_string, s21, "@grzyby"),
		(else_try),
			(eq, ":r2", 3),
			(str_store_string, s21, "@wizytę w szynku"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_5_2"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@w tym kraju"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@w tym województwie"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@tutaj"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_5_3"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Cholera"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@Psia mać"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@Niech to licho"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_5_4"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@zrobiłbym wszystko"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@oddałbym życie"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_r3_2"),
		(val_mod, ":r1",4),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@zwodowałem wczoraj szkutę ze zbożem pod Sandomierzem"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@coraz więcej płótna się  sprzedaje"),
		(else_try),
			(eq, ":r1", 2),
			(str_store_string, s20, "@otworzyłem nowy sklep we Lwowie"),
		(else_try),
			(eq, ":r1", 3),
			(str_store_string, s20, "@dobre plony były w roku ubiegłym"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_r4_2"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1", 0),
			(str_store_string, s20, "@Chłopi mi uciekają z folwarku"),
		(else_try),
			(eq, ":r1", 1),
			(str_store_string, s20, "@długi mam u tutejszego lichwiarza"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_4_7"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@duszno"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@straszna duchota"),
		(else_try),
			(eq, ":r1",2),
			(str_store_string, s20, "@parno"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_greeting_4_8"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@Piękny dzionek"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@Wspaniała pogoda"),
		(else_try),
			(eq, ":r1",2),
			(str_store_string, s20, "@Tak gorąco"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_sim_warchol1_b"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@No dalej"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@Dalej"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_sim_warchol1_1"),
		(val_mod, ":r1",2),
		(val_mod, ":r2",2),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@nicponie"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@łajdaki"),
		(try_end),
		(try_begin),
			(eq, ":r2",0),
			(str_store_string, s21, "@święta"),
		(else_try),
			(eq, ":r2",1),
			(str_store_string, s21, "@parady"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_sim_warchol1_2"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@hołota"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@plebs"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_sim_warchol1_3"),
		(val_mod, ":r1",2),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@gałgany"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@tchórze"),
		(try_end),
	(else_try),
		(eq, ":topic", "str_sim_warchol2_3"),
		(val_mod, ":r1",3),
		(try_begin),
			(eq, ":r1",0),
			(str_store_string, s20, "@We Francji"),
		(else_try),
			(eq, ":r1",1),
			(str_store_string, s20, "@We Włoszech"),
		(else_try),
			(eq, ":r1",2),
			(str_store_string, s20, "@W Anglii"),
		(try_end),

	(try_end),
]),

("cf_narzeka",[
(store_script_param, ":topic", 1),

(this_or_next|eq, ":topic","str_greeting_1_3"),
(this_or_next|eq, ":topic","str_greeting_1_4"),
(this_or_next|eq, ":topic","str_greeting_2_2"),
(this_or_next|eq, ":topic","str_greeting_3_2"),
(this_or_next|eq, ":topic","str_greeting_5_2"),
(this_or_next|eq, ":topic","str_greeting_5_3"),
(this_or_next|eq, ":topic","str_greeting_4_5"),
(this_or_next|eq, ":topic","str_greeting_4_6"),
(this_or_next|eq, ":topic","str_greeting_4_7"),
(this_or_next|eq, ":topic","str_greeting_4_8"),
(eq, ":topic","str_greeting_5_4"),

]),

]