# -*- coding: utf-8 -*-
from ID_items import *
from header_1794troops import *

SzlachtaBegin = "trp_szlachta"
SzlachtaEnd = "trp_biedota"
MieszczaninBegin = "trp_citizen"
MieszczaninEnd = "trp_szlachta"
BiedotaBegin = "trp_biedota"
BiedotaEnd = "trp_dna"

troops1794 = [
   ["brawler_1_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier2],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000007440022d04b2c6cb7d3723d5a00000000001dc90a0000000000000000],
   ["brawler_1_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier_a],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018b102045199c86b7934dc76500000000000886db0000000000000000],
   ["brawler_2_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier3],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001b40c25055c8b7636266d6ce400000000001152a40000000000000000],
   ["brawler_2_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier17],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001840434044a5b31a82b8a990b00000000001549640000000000000000],
   ["brawler_3_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier22],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x0000000fff001404175b6cb68445068300000000001d36dc0000000000000000],
   ["brawler_3_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier29],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001ac08618356a64532ca91372300000000001db6dd0000000000000000],
   ["brawler_4_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier11],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000073600514436db2db6db6db6db00000000001fbb760000000000000000],
   ["brawler_4_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier12],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001ac1015d241a2495764ce22dd00000000001526610000000000000000],
   ["brawler_5_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier14],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001be1001c5425389008c7354cc00000000000a44a50000000000000000],
   ["brawler_5_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier27],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000019f10501346e3313464e6ccec00000000000d44da0000000000000000],
   ["brawler_6_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier4],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018800214f36db6db6db6db6db00000000000db6db0000000000000000],
   ["brawler_6_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier5],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001a210400d36db6db6db6db6db00000000000db6db0000000000000000],
   ["brawler_7_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier16],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018d10100439164f16e7d0534d000000000009baa10000000000000000],
   ["brawler_7_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier6],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001920825d412eb6ac8d9c5b71c000000000011d71b0000000000000000],
   ["brawler_8_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier8],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001b50432454ba272375b59a51f00000000000e56920000000000000000],
   ["brawler_8_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier19],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001a600045157a4974ae330d89500000000001db9210000000000000000],
   ["brawler_9_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier11],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001be1014d437733134eb09466200000000001c2b1a0000000000000000],
   ["brawler_9_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier19],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018b0030510552c6ad1a52d5dc000000000011886a0000000000000000],
   ["brawler_10_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier1],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000073600618536db2db6db6db6db00000000001fbb760000000000000000],
   ["brawler_10_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier18],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001bc0833d036d8b54246cac5b6000000000008b7190000000000000000],
   ["brawler_11_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier17],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001861015433d229e473599baac00000000000e54d40000000000000000],
   ["brawler_11_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier29],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001ac08618356a64532ca91372300000000001db6dd0000000000000000],
   ["brawler_12_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier11],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000073600514436db2db6db6db6db00000000001fbb760000000000000000],
   ["brawler_12_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier12],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001ac1015d241a2495764ce22dd00000000001526610000000000000000],
   ["brawler_13_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier14],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001be1001c5425389008c7354cc00000000000a44a50000000000000000],
   ["brawler_13_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier27],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000019f10501346e3313464e6ccec00000000000d44da0000000000000000],
   ["brawler_14_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier4],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018800214f36db6db6db6db6db00000000000db6db0000000000000000],
   ["brawler_14_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier5],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001a210400d36db6db6db6db6db00000000000db6db0000000000000000],
   ["brawler_15_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier16],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018d10100439164f16e7d0534d000000000009baa10000000000000000],
   ["brawler_15_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier6],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001920825d412eb6ac8d9c5b71c000000000011d71b0000000000000000],
   ["brawler_16_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier8],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001b50432454ba272375b59a51f00000000000e56920000000000000000],
   ["brawler_16_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier19],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001a600045157a4974ae330d89500000000001db9210000000000000000],
   ["brawler_17_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier11],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001be1014d437733134eb09466200000000001c2b1a0000000000000000],
   ["brawler_17_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier19],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018b0030510552c6ad1a52d5dc000000000011886a0000000000000000],
   ["brawler_18_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier10],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000073600618536db2db6db6db6db00000000001fbb760000000000000000],
   ["brawler_18_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier2],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001bc0833d036d8b54246cac5b6000000000008b7190000000000000000],
   ["brawler_19_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier17],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001861015433d229e473599baac00000000000e54d40000000000000000],
   ["brawler_19_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier29],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001ac08618356a64532ca91372300000000001db6dd0000000000000000],
   ["brawler_20_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier11],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000073600514436db2db6db6db6db00000000001fbb760000000000000000],
   ["brawler_20_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier12],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001ac1015d241a2495764ce22dd00000000001526610000000000000000],
   ["brawler_21_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier14],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001be1001c5425389008c7354cc00000000000a44a50000000000000000],
   ["brawler_21_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier27],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000019f10501346e3313464e6ccec00000000000d44da0000000000000000],
   ["brawler_22_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier4],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018800214f36db6db6db6db6db00000000000db6db0000000000000000],
   ["brawler_22_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier5],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001a210400d36db6db6db6db6db00000000000db6db0000000000000000],
   ["brawler_23_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_warchol_a,itm_rapier16],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x000000018d10100439164f16e7d0534d000000000009baa10000000000000000],
   ["brawler_23_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_d,itm_rapier6],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001920825d412eb6ac8d9c5b71c000000000011d71b0000000000000000],
   ["brawler_24_a","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_c,itm_rapier8],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001b50432454ba272375b59a51f00000000000e56920000000000000000],
   ["brawler_24_b","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_cav_pants,itm_polish_coat_e,itm_rapier19],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001a600045157a4974ae330d89500000000001db9210000000000000000],  
   ["brawler_end","Warchoł","Brawlers",tf_hero, 0,reserved, fac_commoners,[itm_warchol_a,itm_rapier_a],def_attrib|str_12|agi_9|level(25),wp(200),knows_common,0x00000001840854c91cec6de92b6e44de00000000000cea8c0000000000000000],


["rabusie_leader","Herszt","Herszt", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_outlaws,
   [itm_austrian_pandur_uniform_a,
	itm_austrian_pandur_shoes,
	itm_austrian_pandur_shoes_a,
	itm_bolts,
	itm_huc1,
    itm_steppe_horse,
	itm_rapier11,
	itm_pistolet1,
    itm_austrian_pandur_cap_a,
	itm_austrian_pandur_cap],
def_attrib|agi_11|level(20),wp(180),knows_ironflesh_4|knows_power_strike_4|knows_riding_3|knows_athletics_2,man_face_middle_1, man_face_older_2],

["zbojnicy_leader","Herszt","Herszt", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_outlaws,
   [itm_austrian_pandur_uniform_a,
	itm_austrian_pandur_shoes,
	itm_austrian_pandur_shoes_a,
	itm_bolts,
	itm_huc1,
    itm_saddle_horse,
	itm_rapier27,
	itm_pistolet1,
    itm_austrian_pandur_cap_a,
	itm_austrian_pandur_cap],
def_attrib|agi_11|level(20),wp(180),knows_ironflesh_4|knows_power_strike_4|knows_riding_3|knows_athletics_2,man_face_middle_1, man_face_older_2],
["przemytnicy_leader","Herszt","Herszt", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_outlaws,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves,itm_bolts,itm_pistolet1,itm_steppe_horse,],
def_attrib|agi_11|level(20),wp(180),knows_ironflesh_4|knows_power_strike_4|knows_riding_3|knows_athletics_2,man_face_middle_1, man_face_older_2],

["przemytnicy","Przemytnik","Przemytnicy", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_horse,0,0,fac_outlaws,
   [itm_austrian_pandur_uniform_a,
    itm_austrian_pandur_uniform,
	itm_austrian_pandur_shoes,
	itm_austrian_pandur_shoes_a,
	itm_head_wrappings,
	itm_wrapping_boots,
	itm_bolts,
	itm_steppe_horse,
    itm_saddle_horse,
	itm_huc1,
	itm_pistolet1,
	itm_rapier14,
	itm_toporek1,
	itm_jatagan1,
    itm_austrian_pandur_cap_a,
	itm_austrian_pandur_cap],
def_attrib|agi_11|level(1),wp(100),knows_ironflesh_2|knows_power_strike_2|knows_riding_1|knows_athletics_2,man_face_middle_1, man_face_older_2],

["zbojnicy","Zbój","Zbójnicy", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_outlaws,
   [itm_austrian_pandur_uniform_a,
    itm_austrian_pandur_uniform,
	itm_austrian_pandur_shoes,
	itm_austrian_pandur_shoes_a,
	itm_head_wrappings,
	itm_wrapping_boots,
	itm_bolts,
	itm_steppe_horse,
    itm_saddle_horse,
	itm_huc1,
	itm_pistolet1,
	itm_rapier14,
	itm_toporek1,
	itm_jatagan1,
    itm_austrian_pandur_cap_a,
	itm_austrian_pandur_cap],
def_attrib|agi_11|level(1),wp(100),knows_ironflesh_2|knows_power_strike_2|knows_riding_1|knows_athletics_2,man_face_middle_1, man_face_older_2],

["qprzyczolekt1","Antoni Hołowaty","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_e,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],

["qprzewrott1","Przewrot1","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["qprzewrott2","Przewrot2","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],


["gListt1","Nieznajomy","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["gListt2","Nieznajomy","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_c,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["gListt3","Nieznajomy","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_b,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],

["qinfiltracjat1","Bandyta","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_austrian_pandur_shoes_a,itm_austrian_pandur_uniform,itm_rapier11],
def_attrib|agi_11|level(10),wp(180),knows_common, 0x000000076e0c61885a9254995badbae300000000001166990000000000000000],
["qinfiltracjat2","Grzegorz Opalonka","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(15),wp(190),knows_common, 0x0000000741005045671155c69646b8f400000000001e275a0000000000000000],


["qemisariuszt1","Emisariusz","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["qemisariuszt2","Chłop","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["qemisariuszt3","Chłop","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["qemisariuszt4","Chłop","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["qemisariuszt5","Chłop","Szpieg", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(1),wp(130),knows_common,man_face_middle_1, man_face_older_2],


  ["town_1_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_2_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_3_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_4_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_5_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_6_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_7_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_8_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_9_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_10_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_11_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_12_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_13_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_14_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_15_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_16_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_17_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_18_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_19_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_20_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_21_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_22_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_23_rusznikarz", "Rusznikarz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],

  ["town_1_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_2_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_3_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_4_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_5_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_6_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_7_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_8_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_9_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_10_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_11_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_12_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_13_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_14_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_15_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_16_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_17_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_18_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_19_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_20_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_21_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_22_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_23_platnerz", "Płatnerz","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],


  ["town_1_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_2_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_3_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_4_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_5_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_6_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_7_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_8_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_9_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_10_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_11_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_12_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_13_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_14_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_15_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_16_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_17_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_18_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_19_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_20_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_21_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_22_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_23_stroje", "Handlarz Strojów","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],

  ["town_1_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_2_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_3_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_4_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_5_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_6_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_7_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_8_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_9_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_10_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_11_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_12_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_13_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_14_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_15_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_16_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_17_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_18_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_19_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_20_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_21_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_22_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_red_gambeson,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],
  ["town_23_konie", "Handlarz Koni","{!}Merchant",          tf_hero|tf_randomize_face|tf_is_merchant, 0,0, fac_commoners,     [itm_leather_jacket,  itm_leather_boots],def_attrib|level(2),wp(20),knows_inventory_management_10, man_face_young_1, man_face_older_2],

  
  ["karczma_karczmarz","Karczmarz","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_leather_apron, itm_leather_boots, itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],  
  ["karczma_szlachta","Szlachcic","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_zupan_e,itm_zupan_f,itm_polish_coat_c,itm_zupan_a, itm_zupan_c, itm_polish_coat_d, itm_polish_coat_e, itm_zupan,itm_cav_pants,itm_civil_pants,itm_civil_pants_a,itm_civil_pants_b, itm_zupan_d,itm_zupan_e,itm_zupan_f,itm_rapier15,itm_scimitar,itm_rapier22,itm_rapier12,itm_rapier19,itm_karabela,itm_rapier24,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],  
  ["karczma_chlopi","Biedak","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_polish_coat_a,itm_polish_coat_b,itm_civil_pants],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_kupcy","Biedak","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_frock_b, itm_frock_c, itm_civil_pants, itm_frock_a,itm_civil_pants_a,itm_civil_pants_b, itm_polish_coat_a, itm_polish_coat_b,itm_frock_e, itm_frock_d],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
   
  ["karczma_dziad_1","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_2","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_3","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_4","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_5","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_6","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_7","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_8","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_9","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],
  ["karczma_dziad_10","Wędrowny dziad","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_pilgrim_disguise,itm_pilgrim_hood,itm_wrapping_boots,],
   def_attrib|level(4),wp(60),knows_common,man_face_older_1, man_face_old_2],


  ["karczma_lowca_1","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_2","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_3","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_4","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_5","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_6","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_7","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_8","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_9","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_10","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_11","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_12","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_13","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_14","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_15","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_16","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_17","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_18","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_19","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_20","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_21","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_22","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_23","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_24","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_25","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_26","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_27","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_28","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_29","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_30","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_31","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_32","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
  ["karczma_lowca_end","Łowca głów","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_red_gambeson,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],


["Zdradat1","Piotr Ożarowski","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_cav_armour,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(20),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["Zdradat2","Józef Ankwicz","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_cav_armour,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(20),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["Zdradat3","Józef Zabiełło","Szpieg", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_cav_armour,itm_rapier11,itm_leather_gloves],
def_attrib|agi_11|level(20),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["porwanakobieta","Dama","Dama", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves|tf_female,0,0,fac_neutral,
[itm_red_dress,itm_blue_hose],
def_attrib|level(1),wp(10),knows_common,swadian_woman_face_1, swadian_woman_face_2],
["dama","Dama","Dama", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves|tf_female,0,0,fac_neutral,
[itm_red_dress,itm_blue_hose],
def_attrib|level(1),wp(10),knows_common,swadian_woman_face_1, swadian_woman_face_2],
["ojciec","Piotr Jabłonowski","Piotr Jabłonowski", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_karabela],
def_attrib|level(8),wp(50),knows_common, 0x0000000fff00120536db6db6db6db6db00000000001db6db0000000000000000],
["jan","Jan","Jan", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(1),wp(5),knows_common,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],
["tukaj","Grzegorz Jabłonowski","Grzegorz Jabłonowski", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_e,itm_kosciuszkowska_szabla],
def_attrib|level(10),wp(135),knows_common, 0x00000005fb00408369f36f6f7d6ef7fe00000000001db6db0000000000000000],
["karczmarz","Wlasciciel Karczmy","Wlasciciel Karczmy", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_leather_apron,itm_civil_pants],
def_attrib|level(1),wp(5),knows_common, 0x000000083b00420669f36f6fe76e472c00000000001db6db0000000000000000],
["odbiorca_listu","Odbiorca listu","Wlasciciel Karczmy", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_red_gambeson,itm_leather_boots],
def_attrib|level(1),wp(5),knows_common, 0x000000093f0000003cdb6db6db6db6db00000000001c06af0000000000000000],
["niemcewicz","Julian Ursyn Niemcewicz","Julian Ursyn Niemcewicz", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_frock_a,itm_austrian_fusiliers_shoes],
def_attrib|level(8),wp(50),knows_common,0x000000083b00000669f36f6f6d6e472c00000000001db6db0000000000000000],
["iksinski","Albert Sapieha","Albert Sapieha", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants,itm_zupan_f,itm_karabela],
def_attrib|level(8),wp(50),knows_common, 0x00000001940c2250352409c55bd5c07700000000001e6b1b0000000000000000],
["dowodca1","Alexander Radishchev","Alexander Radishchev", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_rapier15,itm_frock_a,itm_austrian_fusiliers_shoes],
def_attrib|level(8),wp(50),knows_common,0x00000001b30430c134e365a2ac79e2eb00000000001e38da0000000000000000],
["dowodca2","Ignac Martinovics","Ignac Martinovics", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_frock_b,itm_leather_boots],
def_attrib|level(8),wp(50),knows_common, 0x000000018000319236db6db6db6db6e600000000001c16db0000000000000000],
["dowodca3","General","General", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_rapier15,itm_red_gambeson,itm_leather_boots],
def_attrib|level(8),wp(50),knows_common, 0x00000001810c44064ae591bda2a9851c00000000000a26dc0000000000000000],

["dowodca4","Ferenc Bartok","Ksiądz Ferenc Bartok", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_rapier15,itm_red_gambeson,itm_leather_boots],
def_attrib|level(8),wp(50),knows_common, 0x0000000b170032465f5d769c612cfaec00000000001fcaa30000000000000000],

["sekretarz","Sekretarz","Sekretarz", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_sword_viking_1,itm_zupan_f,itm_leather_boots],
def_attrib|level(8),wp(50),knows_common,man_face_middle_1, man_face_older_2],
["carski_urzednik","Carski Urzędnik","Carski Urzędnik", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_cav_pants,itm_chieftain,itm_french_rapier,itm_leather_gloves],
def_attrib|level(8),wp(50),knows_common,man_face_middle_1, man_face_older_2],
["qszpieg","Szpieg","Herszt", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_d,itm_french_rapier,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common|knows_pathfinding_7|knows_tracking_9,man_face_middle_1, man_face_older_2],
["herszt_bandytow","Herszt Bandytów","Herszt", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_chieftain,itm_rapier11,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common,0x00000001ab0451064adc0e3dcb953a6400000000001436ec0000000000000000],
["zasadzka","Przywódca Zasadzki","Herszt", tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_e,itm_karabela,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common, 0x00000001b6105208271d4e187290a6b2000000000012e8ea0000000000000000],
["ataman","Ataman","Herszt", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_e,itm_karabela,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["werbownik_wegry","werbownik_wegry","Herszt", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_e,itm_karabela,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common,man_face_middle_1, man_face_older_2],
["dowodca3_patrol","Dowódca patrolu","DP", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_c,itm_karabela,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common, 0x00000001ae04358d6df0ffff7ffffff700000000001eefff0000000000000000],

["dowodca4_guard","Gospodyni"," ", tf_hero|tf_female|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
[itm_cav_pants,itm_polish_coat_e,itm_leather_gloves],
def_attrib|level(20),wp(130),knows_common, 0x0000000fff0000037ff56db6db6db6db00000000001fcf3d0000000000000000],

["przywodca_twierdzy","Dowódca Garnizonu"," ", tf_hero|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves,0,0,fac_neutral,
   [itm_polish_fusiliers_coat,
    itm_polish_fusilier_cap,
	itm_polish_fusiliers_pants],
def_attrib|level(20),wp(130),knows_common, 0x000000018b04010568ad7294e3a33a9b00000000000e24bb0000000000000000],

 ["citizen","Mieszczanin","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_frock_b, itm_frock_c, itm_civil_pants, itm_frock_a,itm_civil_pants_a,itm_civil_pants_b, itm_polish_coat_a, itm_polish_coat_b,itm_frock_e, itm_frock_d],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
 ["citizen_f","Mieszczka","Townswomen",tf_female|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_dress, itm_woolen_hose, itm_blue_hose],
   def_attrib|level(2),wp(40),knows_common,woman_face_1,woman_face_2],
 ["szlachta","Szlachcic","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_zupan_e,itm_zupan_f,itm_polish_coat_c, itm_zupan_a, itm_zupan_c, itm_polish_coat_d, itm_polish_coat_e, itm_zupan,itm_cav_pants,itm_civil_pants,itm_civil_pants_a,itm_civil_pants_b, itm_zupan_d,itm_rapier15,itm_rapier17,itm_rapier22,itm_rapier12,itm_rapier19,itm_rapier27,itm_rapier24,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
 ["szlachta_f","Szlachcianka","Szlachcianki",tf_female|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_dress, itm_woolen_hose, itm_blue_hose],
   def_attrib|level(2),wp(40),knows_common,woman_face_1,woman_face_2],
 ["arystokrata_f","Arystokratka","Arystokratki",tf_female|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_dress, itm_woolen_hose, itm_blue_hose],
   def_attrib|level(2),wp(40),knows_common,woman_face_1,woman_face_2],
 ["biedota","Biedak","Townsmen",tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_polish_coat_a,itm_polish_coat_b,itm_civil_pants, itm_leather_jacket,],
   def_attrib|level(4),wp(60),knows_common,man_face_young_1, man_face_old_2],
 ["biedota_f","Biedak","Townswomen",tf_female|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_commoners,
   [itm_polish_coat_a,],
   def_attrib|level(2),wp(40),knows_common,woman_face_1,woman_face_2],
   
["dna","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["gender","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["name","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["surname","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["relation","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["group","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["group_troop","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["know","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["lover","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     

["eps","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["lovers","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["prior1","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["prior2","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["prior3","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     

   ["gListg1","Oficer Straży","Oficer Straży",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_pistol,
    itm_cartridges,
	itm_rapier_a,
    itm_russian_officers_coat,
    itm_russian_officers_pants,
	itm_russian_officers_cap],
   str_9 | agi_6 | int_10 | cha_6|level(14),wp_one_handed (140)| wp_firearm (150) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   ["qrozpoznanieogniemt1","Emisariusz","Oficer Straży",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_pistol,
    itm_cartridges,
	itm_rapier_a,
	itm_frock_c, 
	itm_civil_pants], 
   str_9 | agi_6 | int_10 | cha_6|level(14),wp_one_handed (140)| wp_firearm (150) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   ["qrozpoznanieogniemt2","przeciwnik1","Oficer Straży",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_pistol,
    itm_cartridges,
	itm_rapier_a,
	itm_frock_c, 
	itm_civil_pants],
   str_9 | agi_6 | int_10 | cha_6|level(14),wp_one_handed (140)| wp_firearm (150) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   ["qrozpoznanieogniemt3","przeciwnik2","Oficer Straży",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_pistol,
    itm_cartridges,
	itm_rapier_a,
	itm_frock_b, 
	itm_civil_pants],
   str_9 | agi_6 | int_10 | cha_6|level(14),wp_one_handed (140)| wp_firearm (150) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["gListg2","Straż","Straż",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_rifle,
    itm_rus_fus_coat,
    itm_rus_fus_helmet,
    itm_bolts,
	itm_rus_fus_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_one_handed (170)| wp_firearm (130) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["qdostarczbron2_1","Konspirator","Konspirator",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_rifle,
    itm_rus_fus_coat,
    itm_polish_fusilier_cap,
    itm_bolts,
	itm_polish_fusiliers_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_one_handed (170)| wp_firearm (130) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
  
  ["qdostarczbron2_2","Konspirator","Konspirator",tf_guarantee_ranged|tf_guarantee_helmet|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_kingdom_1,
   [itm_flintlock_rifle,
    itm_rus_fus_coat,
    itm_polish_fusilier_cap,
    itm_bolts,
	itm_polish_fusiliers_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_one_handed (170)| wp_firearm (130) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
  
  
  ["prussian_execution_officer","Pruski Oficer","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
	[itm_prussian_officers_coat_a,
	itm_prussian_officers_pants_a,
	itm_prussian_officers_cap_a,
	itm_rapier_a, itm_pistol, 
	itm_cartridges,],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["russian_execution_officer","Rosyjski Oficer","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
   [itm_flintlock_pistol, itm_cartridges,itm_rapier_c,
    itm_prussian_officers_coat,
    itm_prussian_officers_pants,
	itm_prussian_officers_cap],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["austrian_execution_officer","Austriacki Oficer","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
	[itm_austrian_officers_coat,
	itm_austrian_officers_pants,
	itm_austrian_officers_cap,
	itm_rapier_a, itm_pistol, 
	itm_cartridges,],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["russian_executioner","Rosyjski Strzelec","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
   [itm_execution_rifle,
   itm_russian_jaeger_coat,
   itm_russian_jaeger_cap,
	itm_bolts_a,
	itm_russian_jaeger_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["prussian_executioner","Pruski Strzelec","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
   [itm_prussian_infantry_cap,
    itm_prussian_infantry_coat,
	itm_bolts,
    itm_1782_rifle,
	itm_prussian_infantry_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["austrian_executioner","Austriacki Strzelec","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
   [itm_execution_rifle,
    itm_austrian_fusiliers_uniform,
    itm_austrian_fusiliers_cap,
	itm_bolts_a,
	itm_austrian_fusiliers_shoes],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],

 ["austrian_executioner","Rosyjski Jegier","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
   [itm_execution_rifle,
    itm_russian_jaeger_coat,
    itm_russian_jaeger_cap,
	itm_bolts_a,
	itm_russian_jaeger_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_power_draw_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
  ["polish_executioner","Rosyjski Strzelec","Rosyjscy Jegrzy",tf_guarantee_ranged|tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_helmet,0,0,fac_kingdom_2,
   [itm_execution_rifle,
   itm_russian_jaeger_coat,
   itm_russian_jaeger_cap,
	itm_bolts_a,
	itm_russian_jaeger_pants],
   str_13 | agi_8 | int_15 | cha_6|level(20),wp_polearm (130)| wp_crossbow (250) ,knows_ironflesh_1|knows_athletics_3,nord_face_young_1, nord_face_old_2],
   
["wozny_sadowy","Woźny Sądowy","Woźny Sądowy", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(1),wp(5),knows_common,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],

["wozny_sadowy_a","Mieszczanin","Woźny Sądowy", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(1),wp(5),knows_common,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],

["konspiratorzy","Konspirator","Konspiratorzy", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(1),wp(5),knows_common,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],

["targowiczanie","Targowiczanin","Targowiczanie", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(1),wp(5),knows_common,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],

["uciekinier","Chorąży Świstacki","Uciekinier", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(1),wp(5),knows_common,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],

["rywal","Rywal","Rywal", tf_hero|tf_guarantee_boots|tf_guarantee_armor,0,0,fac_neutral,
[itm_polish_uhlan_pants, itm_frock_a,],
def_attrib|level(10),wp(225),knows_ironflesh_2,0x0000000d7f00014836db6db6db6db6db00000000001db6db0000000000000000],

###############################
###DODAWAC PRZED TYM!!!!#######
###############################
["objects","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0], 
["random_events","objects","objects",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["ranking_sword","ranking","ranking",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["ranking_pistol","ranking","ranking",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
["end","ranking","ranking",tf_hero, 0,0, fac_commoners,[],def_attrib|level(2),wp(20),knows_inventory_management_10,0],     
]
